# Generated by Django 4.1.4 on 2022-12-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='items',
            field=models.IntegerField(null=True),
        ),
    ]
