# Generated by Django 4.1.4 on 2022-12-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender_is_male', models.BooleanField(default=False, verbose_name='Male')),
                ('gender_is_female', models.BooleanField(default=False, verbose_name='Female')),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField()),
                ('material_book', models.BooleanField(default=False, verbose_name='Note Book')),
                ('material_pen', models.BooleanField(default=False, verbose_name='Pen')),
                ('material_paper', models.BooleanField(default=False, verbose_name='Exam Paper')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.purpose')),
            ],
        ),
    ]
