# Generated by Django 4.1.4 on 2022-12-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
