# Generated by Django 4.1.4 on 2022-12-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_details_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AlterField(
            model_name='detail',
            name='gender_is_female',
            field=models.BooleanField(default=False, null=True, verbose_name='Female'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='gender_is_male',
            field=models.BooleanField(default=False, null=True, verbose_name='Male'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='material_book',
            field=models.BooleanField(default=False, null=True, verbose_name='Note Book'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='material_paper',
            field=models.BooleanField(default=False, null=True, verbose_name='Exam Paper'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='material_pen',
            field=models.BooleanField(default=False, null=True, verbose_name='Pen'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
